##################################################
# 根据原来的xxxxxDesc.cpp文件，生成TID的枚举序列
# 依赖原FTCPPackageDesc.cpp中的TID的顺序
# date: 2017-5-16
# powered by cgm
# 用法: 本脚本只根据FTCPPackageDesc.cpp文件,进行生成
#       生成TID序列，生成后，可手动复制粘贴到目标文件中
#       对于TID的名字，可以手动进一步修改    
##################################################

src_file="./desc.cpp"
tmp_file="./tmp.tmp"
targe_file="./tid_def_gen_by_tool.h"
let total_tid=0
let line_num=0
let total_line=`cat $src_file|wc -l`

rm -f $targe_file

echo "//////////////////////////////////////////////////" >> $targe_file
echo "// `date +%Y%m%d`" >> $targe_file
echo "// generated by $0" >> $targe_file
echo "//////////////////////////////////////////////////" >> $targe_file

echo "" >>  $targe_file
echo "const int32_t BUSI_TID_PREFIX = 80000000;" >>  $targe_file
echo "" >>  $targe_file
echo "enum busi_tid : int32_t" >>  $targe_file
echo "{" >>  $targe_file
#printf "    TID_BUSI_PREFIX = TID_BUSI_START,\t\t// 业务TID前缀数值\n" >> $targe_file

while read aline
do
#	echo "line content: "$aline
	# 这行有多种写法
	tid=`expr "$aline" : '\s*{\(TID_.*\),{'`
	if [[ "$tid" != "" ]]; then
		cmnt=`echo "$aline" | cut -d '"' -f 2`
#		echo $cmnt
		if [ $total_tid -eq 0 ]; then
		printf "    $tid = BUSI_TID_PREFIX+1,\t\t//$cmnt\n" >> $targe_file
		else
		printf "    $tid,\t\t//$cmnt\n" >> $targe_file
		fi
		let total_tid++
	fi

	let line_num++
	let percent=0
	percent=`awk -v x=$line_num -v y=$total_line 'BEGIN{printf "%02d",x/y*100}'`
	printf " [In process]:$line_num/$total_line ($percent%%)\r"
done < $src_file

printf "    BUSI_TID_MAX_NUM,\t\t// 业务TID的个数\n" >> $targe_file
echo "};" >> $targe_file
echo "" >>  $targe_file
echo "// There are $total_tid TID in total" >> $targe_file
echo "// Attention! This number is reliable depens on nobody modify this file manually!" >> $targe_file
echo '// You can use "BUSI_TID_MAX_NUM" to know how many TIDs!' >> $targe_file
echo "" >>  $targe_file

